spring:
  main:
    allow-bean-definition-overriding: true
  mvc:
    throw-exception-if-no-handler-found: true
  servlet:
    multipart:
      enabled: true
      max-request-size: "2MB"
      max-file-size: "2MB"
  cloud:
    loadbalancer:
      retry:
        enabled: true
  #session共享
  session:
    store-type: redis
    timeout: PT2H
  data:
    redis:
      repositories:
        enabled: true
  # Redis数据库
  redis:
    database: 0
    # Redis服务器地址
    host: localhost
    # Redis服务器连接端口
    port: 6379
#    # Redis服务器连接密码（默认为空）
#    password: 123456
    # 连接超时时间（毫秒）
    timeout: 2000
    lettuce:
      # 连接池最大连接数（使用负值表示没有限制）
      pool:
        max-active: 2000
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 5